/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import type {
  AccountMeta,
  AccountSignerMeta,
  Address,
  FixedSizeCodec,
  FixedSizeDecoder,
  FixedSizeEncoder,
  Instruction,
  InstructionWithAccounts,
  InstructionWithData,
  ReadonlyAccount,
  ReadonlySignerAccount,
  ReadonlyUint8Array,
  TransactionSigner,
  WritableAccount,
} from "@solana/kit";
import type { ResolvedAccount } from "../shared/index.js";
import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  transformEncoder,
} from "@solana/kit";
import { VOTE_MARKET_PROGRAM_ADDRESS } from "../programs/index.js";
import { getAccountMetaFactory } from "../shared/index.js";

export const CLAIM_TO_REWARD_ACCUMULATOR_DISCRIMINATOR = new Uint8Array([
  224, 2, 107, 127, 245, 68, 3, 89,
]);

export function getClaimToRewardAccumulatorDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CLAIM_TO_REWARD_ACCUMULATOR_DISCRIMINATOR,
  );
}

export type ClaimToRewardAccumulatorInstruction<
  TProgram extends string = typeof VOTE_MARKET_PROGRAM_ADDRESS,
  TAccountScriptAuthority extends string | AccountMeta<string> = string,
  TAccountSeller extends string | AccountMeta<string> = string,
  TAccountSellerTokenAccount extends string | AccountMeta<string> = string,
  TAccountTokenVault extends string | AccountMeta<string> = string,
  TAccountTreasury extends string | AccountMeta<string> = string,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountVoteBuy extends string | AccountMeta<string> = string,
  TAccountVoteDelegate extends string | AccountMeta<string> = string,
  TAccountEscrow extends string | AccountMeta<string> = string,
  TAccountGaugemeister extends string | AccountMeta<string> = string,
  TAccountGaugeVoter extends string | AccountMeta<string> = string,
  TAccountGaugeVote extends string | AccountMeta<string> = string,
  TAccountEpochGaugeVoter extends string | AccountMeta<string> = string,
  TAccountGauge extends string | AccountMeta<string> = string,
  TAccountEpochGauge extends string | AccountMeta<string> = string,
  TAccountEpochGaugeVote extends string | AccountMeta<string> = string,
  TAccountGaugeProgram extends string | AccountMeta<string> = string,
  TAccountLockedVoterProgram extends string | AccountMeta<string> = string,
  TAccountRewardAccumulatorConfig extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountScriptAuthority extends string
        ? ReadonlySignerAccount<TAccountScriptAuthority> &
            AccountSignerMeta<TAccountScriptAuthority>
        : TAccountScriptAuthority,
      TAccountSeller extends string
        ? WritableAccount<TAccountSeller>
        : TAccountSeller,
      TAccountSellerTokenAccount extends string
        ? WritableAccount<TAccountSellerTokenAccount>
        : TAccountSellerTokenAccount,
      TAccountTokenVault extends string
        ? WritableAccount<TAccountTokenVault>
        : TAccountTokenVault,
      TAccountTreasury extends string
        ? WritableAccount<TAccountTreasury>
        : TAccountTreasury,
      TAccountAdmin extends string
        ? ReadonlyAccount<TAccountAdmin>
        : TAccountAdmin,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountVoteBuy extends string
        ? WritableAccount<TAccountVoteBuy>
        : TAccountVoteBuy,
      TAccountVoteDelegate extends string
        ? WritableAccount<TAccountVoteDelegate>
        : TAccountVoteDelegate,
      TAccountEscrow extends string
        ? ReadonlyAccount<TAccountEscrow>
        : TAccountEscrow,
      TAccountGaugemeister extends string
        ? ReadonlyAccount<TAccountGaugemeister>
        : TAccountGaugemeister,
      TAccountGaugeVoter extends string
        ? ReadonlyAccount<TAccountGaugeVoter>
        : TAccountGaugeVoter,
      TAccountGaugeVote extends string
        ? ReadonlyAccount<TAccountGaugeVote>
        : TAccountGaugeVote,
      TAccountEpochGaugeVoter extends string
        ? ReadonlyAccount<TAccountEpochGaugeVoter>
        : TAccountEpochGaugeVoter,
      TAccountGauge extends string
        ? ReadonlyAccount<TAccountGauge>
        : TAccountGauge,
      TAccountEpochGauge extends string
        ? ReadonlyAccount<TAccountEpochGauge>
        : TAccountEpochGauge,
      TAccountEpochGaugeVote extends string
        ? WritableAccount<TAccountEpochGaugeVote>
        : TAccountEpochGaugeVote,
      TAccountGaugeProgram extends string
        ? ReadonlyAccount<TAccountGaugeProgram>
        : TAccountGaugeProgram,
      TAccountLockedVoterProgram extends string
        ? ReadonlyAccount<TAccountLockedVoterProgram>
        : TAccountLockedVoterProgram,
      TAccountRewardAccumulatorConfig extends string
        ? ReadonlyAccount<TAccountRewardAccumulatorConfig>
        : TAccountRewardAccumulatorConfig,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export interface ClaimToRewardAccumulatorInstructionData {
  discriminator: ReadonlyUint8Array;
  epoch: number;
}

export interface ClaimToRewardAccumulatorInstructionDataArgs {
  epoch: number;
}

export function getClaimToRewardAccumulatorInstructionDataEncoder(): FixedSizeEncoder<ClaimToRewardAccumulatorInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["epoch", getU32Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: CLAIM_TO_REWARD_ACCUMULATOR_DISCRIMINATOR,
    }),
  );
}

export function getClaimToRewardAccumulatorInstructionDataDecoder(): FixedSizeDecoder<ClaimToRewardAccumulatorInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["epoch", getU32Decoder()],
  ]);
}

export function getClaimToRewardAccumulatorInstructionDataCodec(): FixedSizeCodec<
  ClaimToRewardAccumulatorInstructionDataArgs,
  ClaimToRewardAccumulatorInstructionData
> {
  return combineCodec(
    getClaimToRewardAccumulatorInstructionDataEncoder(),
    getClaimToRewardAccumulatorInstructionDataDecoder(),
  );
}

export interface ClaimToRewardAccumulatorInput<
  TAccountScriptAuthority extends string = string,
  TAccountSeller extends string = string,
  TAccountSellerTokenAccount extends string = string,
  TAccountTokenVault extends string = string,
  TAccountTreasury extends string = string,
  TAccountAdmin extends string = string,
  TAccountMint extends string = string,
  TAccountConfig extends string = string,
  TAccountVoteBuy extends string = string,
  TAccountVoteDelegate extends string = string,
  TAccountEscrow extends string = string,
  TAccountGaugemeister extends string = string,
  TAccountGaugeVoter extends string = string,
  TAccountGaugeVote extends string = string,
  TAccountEpochGaugeVoter extends string = string,
  TAccountGauge extends string = string,
  TAccountEpochGauge extends string = string,
  TAccountEpochGaugeVote extends string = string,
  TAccountGaugeProgram extends string = string,
  TAccountLockedVoterProgram extends string = string,
  TAccountRewardAccumulatorConfig extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> {
  scriptAuthority: TransactionSigner<TAccountScriptAuthority>;
  seller: Address<TAccountSeller>;
  sellerTokenAccount: Address<TAccountSellerTokenAccount>;
  tokenVault: Address<TAccountTokenVault>;
  /** CHECK Checked by seed constraints */
  treasury: Address<TAccountTreasury>;
  /** CHECK Not enough stack space to deserialize. Only used to check treasury seeds. */
  admin: Address<TAccountAdmin>;
  mint: Address<TAccountMint>;
  config: Address<TAccountConfig>;
  voteBuy: Address<TAccountVoteBuy>;
  voteDelegate: Address<TAccountVoteDelegate>;
  escrow: Address<TAccountEscrow>;
  gaugemeister: Address<TAccountGaugemeister>;
  gaugeVoter: Address<TAccountGaugeVoter>;
  gaugeVote: Address<TAccountGaugeVote>;
  epochGaugeVoter: Address<TAccountEpochGaugeVoter>;
  gauge: Address<TAccountGauge>;
  epochGauge: Address<TAccountEpochGauge>;
  epochGaugeVote: Address<TAccountEpochGaugeVote>;
  gaugeProgram: Address<TAccountGaugeProgram>;
  lockedVoterProgram: Address<TAccountLockedVoterProgram>;
  rewardAccumulatorConfig: Address<TAccountRewardAccumulatorConfig>;
  tokenProgram?: Address<TAccountTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  epoch: ClaimToRewardAccumulatorInstructionDataArgs["epoch"];
}

export function getClaimToRewardAccumulatorInstruction<
  TAccountScriptAuthority extends string,
  TAccountSeller extends string,
  TAccountSellerTokenAccount extends string,
  TAccountTokenVault extends string,
  TAccountTreasury extends string,
  TAccountAdmin extends string,
  TAccountMint extends string,
  TAccountConfig extends string,
  TAccountVoteBuy extends string,
  TAccountVoteDelegate extends string,
  TAccountEscrow extends string,
  TAccountGaugemeister extends string,
  TAccountGaugeVoter extends string,
  TAccountGaugeVote extends string,
  TAccountEpochGaugeVoter extends string,
  TAccountGauge extends string,
  TAccountEpochGauge extends string,
  TAccountEpochGaugeVote extends string,
  TAccountGaugeProgram extends string,
  TAccountLockedVoterProgram extends string,
  TAccountRewardAccumulatorConfig extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof VOTE_MARKET_PROGRAM_ADDRESS,
>(
  input: ClaimToRewardAccumulatorInput<
    TAccountScriptAuthority,
    TAccountSeller,
    TAccountSellerTokenAccount,
    TAccountTokenVault,
    TAccountTreasury,
    TAccountAdmin,
    TAccountMint,
    TAccountConfig,
    TAccountVoteBuy,
    TAccountVoteDelegate,
    TAccountEscrow,
    TAccountGaugemeister,
    TAccountGaugeVoter,
    TAccountGaugeVote,
    TAccountEpochGaugeVoter,
    TAccountGauge,
    TAccountEpochGauge,
    TAccountEpochGaugeVote,
    TAccountGaugeProgram,
    TAccountLockedVoterProgram,
    TAccountRewardAccumulatorConfig,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): ClaimToRewardAccumulatorInstruction<
  TProgramAddress,
  TAccountScriptAuthority,
  TAccountSeller,
  TAccountSellerTokenAccount,
  TAccountTokenVault,
  TAccountTreasury,
  TAccountAdmin,
  TAccountMint,
  TAccountConfig,
  TAccountVoteBuy,
  TAccountVoteDelegate,
  TAccountEscrow,
  TAccountGaugemeister,
  TAccountGaugeVoter,
  TAccountGaugeVote,
  TAccountEpochGaugeVoter,
  TAccountGauge,
  TAccountEpochGauge,
  TAccountEpochGaugeVote,
  TAccountGaugeProgram,
  TAccountLockedVoterProgram,
  TAccountRewardAccumulatorConfig,
  TAccountTokenProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? VOTE_MARKET_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    scriptAuthority: {
      value: input.scriptAuthority ?? null,
      isWritable: false,
    },
    seller: { value: input.seller ?? null, isWritable: true },
    sellerTokenAccount: {
      value: input.sellerTokenAccount ?? null,
      isWritable: true,
    },
    tokenVault: { value: input.tokenVault ?? null, isWritable: true },
    treasury: { value: input.treasury ?? null, isWritable: true },
    admin: { value: input.admin ?? null, isWritable: false },
    mint: { value: input.mint ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: false },
    voteBuy: { value: input.voteBuy ?? null, isWritable: true },
    voteDelegate: { value: input.voteDelegate ?? null, isWritable: true },
    escrow: { value: input.escrow ?? null, isWritable: false },
    gaugemeister: { value: input.gaugemeister ?? null, isWritable: false },
    gaugeVoter: { value: input.gaugeVoter ?? null, isWritable: false },
    gaugeVote: { value: input.gaugeVote ?? null, isWritable: false },
    epochGaugeVoter: {
      value: input.epochGaugeVoter ?? null,
      isWritable: false,
    },
    gauge: { value: input.gauge ?? null, isWritable: false },
    epochGauge: { value: input.epochGauge ?? null, isWritable: false },
    epochGaugeVote: { value: input.epochGaugeVote ?? null, isWritable: true },
    gaugeProgram: { value: input.gaugeProgram ?? null, isWritable: false },
    lockedVoterProgram: {
      value: input.lockedVoterProgram ?? null,
      isWritable: false,
    },
    rewardAccumulatorConfig: {
      value: input.rewardAccumulatorConfig ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.scriptAuthority),
      getAccountMeta(accounts.seller),
      getAccountMeta(accounts.sellerTokenAccount),
      getAccountMeta(accounts.tokenVault),
      getAccountMeta(accounts.treasury),
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.voteBuy),
      getAccountMeta(accounts.voteDelegate),
      getAccountMeta(accounts.escrow),
      getAccountMeta(accounts.gaugemeister),
      getAccountMeta(accounts.gaugeVoter),
      getAccountMeta(accounts.gaugeVote),
      getAccountMeta(accounts.epochGaugeVoter),
      getAccountMeta(accounts.gauge),
      getAccountMeta(accounts.epochGauge),
      getAccountMeta(accounts.epochGaugeVote),
      getAccountMeta(accounts.gaugeProgram),
      getAccountMeta(accounts.lockedVoterProgram),
      getAccountMeta(accounts.rewardAccumulatorConfig),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getClaimToRewardAccumulatorInstructionDataEncoder().encode(
      args as ClaimToRewardAccumulatorInstructionDataArgs,
    ),
    programAddress,
  } as ClaimToRewardAccumulatorInstruction<
    TProgramAddress,
    TAccountScriptAuthority,
    TAccountSeller,
    TAccountSellerTokenAccount,
    TAccountTokenVault,
    TAccountTreasury,
    TAccountAdmin,
    TAccountMint,
    TAccountConfig,
    TAccountVoteBuy,
    TAccountVoteDelegate,
    TAccountEscrow,
    TAccountGaugemeister,
    TAccountGaugeVoter,
    TAccountGaugeVote,
    TAccountEpochGaugeVoter,
    TAccountGauge,
    TAccountEpochGauge,
    TAccountEpochGaugeVote,
    TAccountGaugeProgram,
    TAccountLockedVoterProgram,
    TAccountRewardAccumulatorConfig,
    TAccountTokenProgram,
    TAccountSystemProgram
  >);
}

export interface ParsedClaimToRewardAccumulatorInstruction<
  TProgram extends string = typeof VOTE_MARKET_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> {
  programAddress: Address<TProgram>;
  accounts: {
    scriptAuthority: TAccountMetas[0];
    seller: TAccountMetas[1];
    sellerTokenAccount: TAccountMetas[2];
    tokenVault: TAccountMetas[3];
    /** CHECK Checked by seed constraints */
    treasury: TAccountMetas[4];
    /** CHECK Not enough stack space to deserialize. Only used to check treasury seeds. */
    admin: TAccountMetas[5];
    mint: TAccountMetas[6];
    config: TAccountMetas[7];
    voteBuy: TAccountMetas[8];
    voteDelegate: TAccountMetas[9];
    escrow: TAccountMetas[10];
    gaugemeister: TAccountMetas[11];
    gaugeVoter: TAccountMetas[12];
    gaugeVote: TAccountMetas[13];
    epochGaugeVoter: TAccountMetas[14];
    gauge: TAccountMetas[15];
    epochGauge: TAccountMetas[16];
    epochGaugeVote: TAccountMetas[17];
    gaugeProgram: TAccountMetas[18];
    lockedVoterProgram: TAccountMetas[19];
    rewardAccumulatorConfig: TAccountMetas[20];
    tokenProgram: TAccountMetas[21];
    systemProgram: TAccountMetas[22];
  };
  data: ClaimToRewardAccumulatorInstructionData;
}

export function parseClaimToRewardAccumulatorInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedClaimToRewardAccumulatorInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 23) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      scriptAuthority: getNextAccount(),
      seller: getNextAccount(),
      sellerTokenAccount: getNextAccount(),
      tokenVault: getNextAccount(),
      treasury: getNextAccount(),
      admin: getNextAccount(),
      mint: getNextAccount(),
      config: getNextAccount(),
      voteBuy: getNextAccount(),
      voteDelegate: getNextAccount(),
      escrow: getNextAccount(),
      gaugemeister: getNextAccount(),
      gaugeVoter: getNextAccount(),
      gaugeVote: getNextAccount(),
      epochGaugeVoter: getNextAccount(),
      gauge: getNextAccount(),
      epochGauge: getNextAccount(),
      epochGaugeVote: getNextAccount(),
      gaugeProgram: getNextAccount(),
      lockedVoterProgram: getNextAccount(),
      rewardAccumulatorConfig: getNextAccount(),
      tokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getClaimToRewardAccumulatorInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
