/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import type {
  AccountMeta,
  AccountSignerMeta,
  Address,
  FixedSizeCodec,
  FixedSizeDecoder,
  FixedSizeEncoder,
  Instruction,
  InstructionWithAccounts,
  InstructionWithData,
  ReadonlyAccount,
  ReadonlyUint8Array,
  TransactionSigner,
  WritableAccount,
  WritableSignerAccount,
} from "@solana/kit";
import type { ResolvedAccount } from "../shared/index.js";
import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  transformEncoder,
} from "@solana/kit";
import { VOTE_MARKET_PROGRAM_ADDRESS } from "../programs/index.js";
import { getAccountMetaFactory } from "../shared/index.js";

export const COMMIT_VOTE_DISCRIMINATOR = new Uint8Array([
  134, 97, 90, 126, 91, 66, 16, 26,
]);

export function getCommitVoteDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(COMMIT_VOTE_DISCRIMINATOR);
}

export type CommitVoteInstruction<
  TProgram extends string = typeof VOTE_MARKET_PROGRAM_ADDRESS,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountScriptAuthority extends string | AccountMeta<string> = string,
  TAccountGaugemeister extends string | AccountMeta<string> = string,
  TAccountGauge extends string | AccountMeta<string> = string,
  TAccountGaugeVoter extends string | AccountMeta<string> = string,
  TAccountGaugeVote extends string | AccountMeta<string> = string,
  TAccountEpochGauge extends string | AccountMeta<string> = string,
  TAccountEpochGaugeVoter extends string | AccountMeta<string> = string,
  TAccountEpochGaugeVote extends string | AccountMeta<string> = string,
  TAccountVoteDelegate extends string | AccountMeta<string> = string,
  TAccountGaugeProgram extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountScriptAuthority extends string
        ? WritableSignerAccount<TAccountScriptAuthority> &
            AccountSignerMeta<TAccountScriptAuthority>
        : TAccountScriptAuthority,
      TAccountGaugemeister extends string
        ? ReadonlyAccount<TAccountGaugemeister>
        : TAccountGaugemeister,
      TAccountGauge extends string
        ? ReadonlyAccount<TAccountGauge>
        : TAccountGauge,
      TAccountGaugeVoter extends string
        ? ReadonlyAccount<TAccountGaugeVoter>
        : TAccountGaugeVoter,
      TAccountGaugeVote extends string
        ? ReadonlyAccount<TAccountGaugeVote>
        : TAccountGaugeVote,
      TAccountEpochGauge extends string
        ? WritableAccount<TAccountEpochGauge>
        : TAccountEpochGauge,
      TAccountEpochGaugeVoter extends string
        ? WritableAccount<TAccountEpochGaugeVoter>
        : TAccountEpochGaugeVoter,
      TAccountEpochGaugeVote extends string
        ? WritableAccount<TAccountEpochGaugeVote>
        : TAccountEpochGaugeVote,
      TAccountVoteDelegate extends string
        ? WritableAccount<TAccountVoteDelegate>
        : TAccountVoteDelegate,
      TAccountGaugeProgram extends string
        ? ReadonlyAccount<TAccountGaugeProgram>
        : TAccountGaugeProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export interface CommitVoteInstructionData {
  discriminator: ReadonlyUint8Array;
  epoch: number;
}

export interface CommitVoteInstructionDataArgs {
  epoch: number;
}

export function getCommitVoteInstructionDataEncoder(): FixedSizeEncoder<CommitVoteInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["epoch", getU32Encoder()],
    ]),
    (value) => ({ ...value, discriminator: COMMIT_VOTE_DISCRIMINATOR }),
  );
}

export function getCommitVoteInstructionDataDecoder(): FixedSizeDecoder<CommitVoteInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["epoch", getU32Decoder()],
  ]);
}

export function getCommitVoteInstructionDataCodec(): FixedSizeCodec<
  CommitVoteInstructionDataArgs,
  CommitVoteInstructionData
> {
  return combineCodec(
    getCommitVoteInstructionDataEncoder(),
    getCommitVoteInstructionDataDecoder(),
  );
}

export interface CommitVoteInput<
  TAccountConfig extends string = string,
  TAccountScriptAuthority extends string = string,
  TAccountGaugemeister extends string = string,
  TAccountGauge extends string = string,
  TAccountGaugeVoter extends string = string,
  TAccountGaugeVote extends string = string,
  TAccountEpochGauge extends string = string,
  TAccountEpochGaugeVoter extends string = string,
  TAccountEpochGaugeVote extends string = string,
  TAccountVoteDelegate extends string = string,
  TAccountGaugeProgram extends string = string,
  TAccountSystemProgram extends string = string,
> {
  config: Address<TAccountConfig>;
  scriptAuthority: TransactionSigner<TAccountScriptAuthority>;
  gaugemeister: Address<TAccountGaugemeister>;
  gauge: Address<TAccountGauge>;
  gaugeVoter: Address<TAccountGaugeVoter>;
  gaugeVote: Address<TAccountGaugeVote>;
  epochGauge: Address<TAccountEpochGauge>;
  epochGaugeVoter: Address<TAccountEpochGaugeVoter>;
  /** CHECK This will be initialized through a CPI */
  epochGaugeVote: Address<TAccountEpochGaugeVote>;
  voteDelegate: Address<TAccountVoteDelegate>;
  gaugeProgram: Address<TAccountGaugeProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  epoch: CommitVoteInstructionDataArgs["epoch"];
}

export function getCommitVoteInstruction<
  TAccountConfig extends string,
  TAccountScriptAuthority extends string,
  TAccountGaugemeister extends string,
  TAccountGauge extends string,
  TAccountGaugeVoter extends string,
  TAccountGaugeVote extends string,
  TAccountEpochGauge extends string,
  TAccountEpochGaugeVoter extends string,
  TAccountEpochGaugeVote extends string,
  TAccountVoteDelegate extends string,
  TAccountGaugeProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof VOTE_MARKET_PROGRAM_ADDRESS,
>(
  input: CommitVoteInput<
    TAccountConfig,
    TAccountScriptAuthority,
    TAccountGaugemeister,
    TAccountGauge,
    TAccountGaugeVoter,
    TAccountGaugeVote,
    TAccountEpochGauge,
    TAccountEpochGaugeVoter,
    TAccountEpochGaugeVote,
    TAccountVoteDelegate,
    TAccountGaugeProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): CommitVoteInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountScriptAuthority,
  TAccountGaugemeister,
  TAccountGauge,
  TAccountGaugeVoter,
  TAccountGaugeVote,
  TAccountEpochGauge,
  TAccountEpochGaugeVoter,
  TAccountEpochGaugeVote,
  TAccountVoteDelegate,
  TAccountGaugeProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? VOTE_MARKET_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: false },
    scriptAuthority: { value: input.scriptAuthority ?? null, isWritable: true },
    gaugemeister: { value: input.gaugemeister ?? null, isWritable: false },
    gauge: { value: input.gauge ?? null, isWritable: false },
    gaugeVoter: { value: input.gaugeVoter ?? null, isWritable: false },
    gaugeVote: { value: input.gaugeVote ?? null, isWritable: false },
    epochGauge: { value: input.epochGauge ?? null, isWritable: true },
    epochGaugeVoter: { value: input.epochGaugeVoter ?? null, isWritable: true },
    epochGaugeVote: { value: input.epochGaugeVote ?? null, isWritable: true },
    voteDelegate: { value: input.voteDelegate ?? null, isWritable: true },
    gaugeProgram: { value: input.gaugeProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.scriptAuthority),
      getAccountMeta(accounts.gaugemeister),
      getAccountMeta(accounts.gauge),
      getAccountMeta(accounts.gaugeVoter),
      getAccountMeta(accounts.gaugeVote),
      getAccountMeta(accounts.epochGauge),
      getAccountMeta(accounts.epochGaugeVoter),
      getAccountMeta(accounts.epochGaugeVote),
      getAccountMeta(accounts.voteDelegate),
      getAccountMeta(accounts.gaugeProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCommitVoteInstructionDataEncoder().encode(
      args as CommitVoteInstructionDataArgs,
    ),
    programAddress,
  } as CommitVoteInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountScriptAuthority,
    TAccountGaugemeister,
    TAccountGauge,
    TAccountGaugeVoter,
    TAccountGaugeVote,
    TAccountEpochGauge,
    TAccountEpochGaugeVoter,
    TAccountEpochGaugeVote,
    TAccountVoteDelegate,
    TAccountGaugeProgram,
    TAccountSystemProgram
  >);
}

export interface ParsedCommitVoteInstruction<
  TProgram extends string = typeof VOTE_MARKET_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> {
  programAddress: Address<TProgram>;
  accounts: {
    config: TAccountMetas[0];
    scriptAuthority: TAccountMetas[1];
    gaugemeister: TAccountMetas[2];
    gauge: TAccountMetas[3];
    gaugeVoter: TAccountMetas[4];
    gaugeVote: TAccountMetas[5];
    epochGauge: TAccountMetas[6];
    epochGaugeVoter: TAccountMetas[7];
    /** CHECK This will be initialized through a CPI */
    epochGaugeVote: TAccountMetas[8];
    voteDelegate: TAccountMetas[9];
    gaugeProgram: TAccountMetas[10];
    systemProgram: TAccountMetas[11];
  };
  data: CommitVoteInstructionData;
}

export function parseCommitVoteInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCommitVoteInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 12) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      scriptAuthority: getNextAccount(),
      gaugemeister: getNextAccount(),
      gauge: getNextAccount(),
      gaugeVoter: getNextAccount(),
      gaugeVote: getNextAccount(),
      epochGauge: getNextAccount(),
      epochGaugeVoter: getNextAccount(),
      epochGaugeVote: getNextAccount(),
      voteDelegate: getNextAccount(),
      gaugeProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getCommitVoteInstructionDataDecoder().decode(instruction.data),
  };
}
