/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import type {
  AccountMeta,
  AccountSignerMeta,
  Address,
  Codec,
  Decoder,
  Encoder,
  Instruction,
  InstructionWithAccounts,
  InstructionWithData,
  ReadonlyAccount,
  ReadonlyUint8Array,
  TransactionSigner,
  WritableAccount,
  WritableSignerAccount,
} from "@solana/kit";
import type { ResolvedAccount } from "../shared/index.js";
import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  transformEncoder,
} from "@solana/kit";
import { VOTE_MARKET_PROGRAM_ADDRESS } from "../programs/index.js";
import { getAccountMetaFactory } from "../shared/index.js";

export const CREATE_CONFIG_DISCRIMINATOR = new Uint8Array([
  201, 207, 243, 114, 75, 111, 47, 189,
]);

export function getCreateConfigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CREATE_CONFIG_DISCRIMINATOR,
  );
}

export type CreateConfigInstruction<
  TProgram extends string = typeof VOTE_MARKET_PROGRAM_ADDRESS,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountGaugemeister extends string | AccountMeta<string> = string,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountAllowedMints extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountConfig extends string
        ? WritableSignerAccount<TAccountConfig> &
            AccountSignerMeta<TAccountConfig>
        : TAccountConfig,
      TAccountGaugemeister extends string
        ? ReadonlyAccount<TAccountGaugemeister>
        : TAccountGaugemeister,
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountAllowedMints extends string
        ? WritableAccount<TAccountAllowedMints>
        : TAccountAllowedMints,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export interface CreateConfigInstructionData {
  discriminator: ReadonlyUint8Array;
  mints: Address[];
  claimFee: number;
  scriptAuthority: Address;
}

export interface CreateConfigInstructionDataArgs {
  mints: Address[];
  claimFee: number;
  scriptAuthority: Address;
}

export function getCreateConfigInstructionDataEncoder(): Encoder<CreateConfigInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["mints", getArrayEncoder(getAddressEncoder())],
      ["claimFee", getU16Encoder()],
      ["scriptAuthority", getAddressEncoder()],
    ]),
    (value) => ({ ...value, discriminator: CREATE_CONFIG_DISCRIMINATOR }),
  );
}

export function getCreateConfigInstructionDataDecoder(): Decoder<CreateConfigInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["mints", getArrayDecoder(getAddressDecoder())],
    ["claimFee", getU16Decoder()],
    ["scriptAuthority", getAddressDecoder()],
  ]);
}

export function getCreateConfigInstructionDataCodec(): Codec<
  CreateConfigInstructionDataArgs,
  CreateConfigInstructionData
> {
  return combineCodec(
    getCreateConfigInstructionDataEncoder(),
    getCreateConfigInstructionDataDecoder(),
  );
}

export interface CreateConfigInput<
  TAccountConfig extends string = string,
  TAccountGaugemeister extends string = string,
  TAccountPayer extends string = string,
  TAccountAllowedMints extends string = string,
  TAccountSystemProgram extends string = string,
> {
  config: TransactionSigner<TAccountConfig>;
  gaugemeister: Address<TAccountGaugemeister>;
  payer: TransactionSigner<TAccountPayer>;
  allowedMints: Address<TAccountAllowedMints>;
  systemProgram?: Address<TAccountSystemProgram>;
  mints: CreateConfigInstructionDataArgs["mints"];
  claimFee: CreateConfigInstructionDataArgs["claimFee"];
  scriptAuthority: CreateConfigInstructionDataArgs["scriptAuthority"];
}

export function getCreateConfigInstruction<
  TAccountConfig extends string,
  TAccountGaugemeister extends string,
  TAccountPayer extends string,
  TAccountAllowedMints extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof VOTE_MARKET_PROGRAM_ADDRESS,
>(
  input: CreateConfigInput<
    TAccountConfig,
    TAccountGaugemeister,
    TAccountPayer,
    TAccountAllowedMints,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): CreateConfigInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountGaugemeister,
  TAccountPayer,
  TAccountAllowedMints,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? VOTE_MARKET_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: true },
    gaugemeister: { value: input.gaugemeister ?? null, isWritable: false },
    payer: { value: input.payer ?? null, isWritable: true },
    allowedMints: { value: input.allowedMints ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.gaugemeister),
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.allowedMints),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCreateConfigInstructionDataEncoder().encode(
      args as CreateConfigInstructionDataArgs,
    ),
    programAddress,
  } as CreateConfigInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountGaugemeister,
    TAccountPayer,
    TAccountAllowedMints,
    TAccountSystemProgram
  >);
}

export interface ParsedCreateConfigInstruction<
  TProgram extends string = typeof VOTE_MARKET_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> {
  programAddress: Address<TProgram>;
  accounts: {
    config: TAccountMetas[0];
    gaugemeister: TAccountMetas[1];
    payer: TAccountMetas[2];
    allowedMints: TAccountMetas[3];
    systemProgram: TAccountMetas[4];
  };
  data: CreateConfigInstructionData;
}

export function parseCreateConfigInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCreateConfigInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      gaugemeister: getNextAccount(),
      payer: getNextAccount(),
      allowedMints: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getCreateConfigInstructionDataDecoder().decode(instruction.data),
  };
}
