/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import type {
  AccountMeta,
  AccountSignerMeta,
  Address,
  FixedSizeCodec,
  FixedSizeDecoder,
  FixedSizeEncoder,
  Instruction,
  InstructionWithAccounts,
  InstructionWithData,
  ReadonlyAccount,
  ReadonlyUint8Array,
  TransactionSigner,
  WritableAccount,
  WritableSignerAccount,
} from "@solana/kit";
import type { ResolvedAccount } from "../shared/index.js";
import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
} from "@solana/kit";
import { VOTE_MARKET_PROGRAM_ADDRESS } from "../programs/index.js";
import { getAccountMetaFactory } from "../shared/index.js";

export const INCREASE_VOTE_BUY_DISCRIMINATOR = new Uint8Array([
  77, 209, 215, 129, 60, 249, 205, 53,
]);

export function getIncreaseVoteBuyDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INCREASE_VOTE_BUY_DISCRIMINATOR,
  );
}

export type IncreaseVoteBuyInstruction<
  TProgram extends string = typeof VOTE_MARKET_PROGRAM_ADDRESS,
  TAccountBuyer extends string | AccountMeta<string> = string,
  TAccountBuyerTokenAccount extends string | AccountMeta<string> = string,
  TAccountTokenVault extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountGaugemeister extends string | AccountMeta<string> = string,
  TAccountVoteBuy extends string | AccountMeta<string> = string,
  TAccountGauge extends string | AccountMeta<string> = string,
  TAccountAllowedMints extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountAssociatedTokenProgram extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountBuyer extends string
        ? WritableSignerAccount<TAccountBuyer> &
            AccountSignerMeta<TAccountBuyer>
        : TAccountBuyer,
      TAccountBuyerTokenAccount extends string
        ? WritableAccount<TAccountBuyerTokenAccount>
        : TAccountBuyerTokenAccount,
      TAccountTokenVault extends string
        ? WritableAccount<TAccountTokenVault>
        : TAccountTokenVault,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountGaugemeister extends string
        ? ReadonlyAccount<TAccountGaugemeister>
        : TAccountGaugemeister,
      TAccountVoteBuy extends string
        ? WritableAccount<TAccountVoteBuy>
        : TAccountVoteBuy,
      TAccountGauge extends string
        ? ReadonlyAccount<TAccountGauge>
        : TAccountGauge,
      TAccountAllowedMints extends string
        ? ReadonlyAccount<TAccountAllowedMints>
        : TAccountAllowedMints,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export interface IncreaseVoteBuyInstructionData {
  discriminator: ReadonlyUint8Array;
  epoch: number;
  amount: bigint;
}

export interface IncreaseVoteBuyInstructionDataArgs {
  epoch: number;
  amount: number | bigint;
}

export function getIncreaseVoteBuyInstructionDataEncoder(): FixedSizeEncoder<IncreaseVoteBuyInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["epoch", getU32Encoder()],
      ["amount", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: INCREASE_VOTE_BUY_DISCRIMINATOR }),
  );
}

export function getIncreaseVoteBuyInstructionDataDecoder(): FixedSizeDecoder<IncreaseVoteBuyInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["epoch", getU32Decoder()],
    ["amount", getU64Decoder()],
  ]);
}

export function getIncreaseVoteBuyInstructionDataCodec(): FixedSizeCodec<
  IncreaseVoteBuyInstructionDataArgs,
  IncreaseVoteBuyInstructionData
> {
  return combineCodec(
    getIncreaseVoteBuyInstructionDataEncoder(),
    getIncreaseVoteBuyInstructionDataDecoder(),
  );
}

export interface IncreaseVoteBuyInput<
  TAccountBuyer extends string = string,
  TAccountBuyerTokenAccount extends string = string,
  TAccountTokenVault extends string = string,
  TAccountMint extends string = string,
  TAccountConfig extends string = string,
  TAccountGaugemeister extends string = string,
  TAccountVoteBuy extends string = string,
  TAccountGauge extends string = string,
  TAccountAllowedMints extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> {
  buyer: TransactionSigner<TAccountBuyer>;
  buyerTokenAccount: Address<TAccountBuyerTokenAccount>;
  tokenVault: Address<TAccountTokenVault>;
  mint: Address<TAccountMint>;
  config: Address<TAccountConfig>;
  gaugemeister: Address<TAccountGaugemeister>;
  voteBuy: Address<TAccountVoteBuy>;
  gauge: Address<TAccountGauge>;
  allowedMints: Address<TAccountAllowedMints>;
  tokenProgram?: Address<TAccountTokenProgram>;
  associatedTokenProgram: Address<TAccountAssociatedTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  epoch: IncreaseVoteBuyInstructionDataArgs["epoch"];
  amount: IncreaseVoteBuyInstructionDataArgs["amount"];
}

export function getIncreaseVoteBuyInstruction<
  TAccountBuyer extends string,
  TAccountBuyerTokenAccount extends string,
  TAccountTokenVault extends string,
  TAccountMint extends string,
  TAccountConfig extends string,
  TAccountGaugemeister extends string,
  TAccountVoteBuy extends string,
  TAccountGauge extends string,
  TAccountAllowedMints extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof VOTE_MARKET_PROGRAM_ADDRESS,
>(
  input: IncreaseVoteBuyInput<
    TAccountBuyer,
    TAccountBuyerTokenAccount,
    TAccountTokenVault,
    TAccountMint,
    TAccountConfig,
    TAccountGaugemeister,
    TAccountVoteBuy,
    TAccountGauge,
    TAccountAllowedMints,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): IncreaseVoteBuyInstruction<
  TProgramAddress,
  TAccountBuyer,
  TAccountBuyerTokenAccount,
  TAccountTokenVault,
  TAccountMint,
  TAccountConfig,
  TAccountGaugemeister,
  TAccountVoteBuy,
  TAccountGauge,
  TAccountAllowedMints,
  TAccountTokenProgram,
  TAccountAssociatedTokenProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? VOTE_MARKET_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    buyer: { value: input.buyer ?? null, isWritable: true },
    buyerTokenAccount: {
      value: input.buyerTokenAccount ?? null,
      isWritable: true,
    },
    tokenVault: { value: input.tokenVault ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: false },
    gaugemeister: { value: input.gaugemeister ?? null, isWritable: false },
    voteBuy: { value: input.voteBuy ?? null, isWritable: true },
    gauge: { value: input.gauge ?? null, isWritable: false },
    allowedMints: { value: input.allowedMints ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.buyer),
      getAccountMeta(accounts.buyerTokenAccount),
      getAccountMeta(accounts.tokenVault),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.gaugemeister),
      getAccountMeta(accounts.voteBuy),
      getAccountMeta(accounts.gauge),
      getAccountMeta(accounts.allowedMints),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getIncreaseVoteBuyInstructionDataEncoder().encode(
      args as IncreaseVoteBuyInstructionDataArgs,
    ),
    programAddress,
  } as IncreaseVoteBuyInstruction<
    TProgramAddress,
    TAccountBuyer,
    TAccountBuyerTokenAccount,
    TAccountTokenVault,
    TAccountMint,
    TAccountConfig,
    TAccountGaugemeister,
    TAccountVoteBuy,
    TAccountGauge,
    TAccountAllowedMints,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >);
}

export interface ParsedIncreaseVoteBuyInstruction<
  TProgram extends string = typeof VOTE_MARKET_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> {
  programAddress: Address<TProgram>;
  accounts: {
    buyer: TAccountMetas[0];
    buyerTokenAccount: TAccountMetas[1];
    tokenVault: TAccountMetas[2];
    mint: TAccountMetas[3];
    config: TAccountMetas[4];
    gaugemeister: TAccountMetas[5];
    voteBuy: TAccountMetas[6];
    gauge: TAccountMetas[7];
    allowedMints: TAccountMetas[8];
    tokenProgram: TAccountMetas[9];
    associatedTokenProgram: TAccountMetas[10];
    systemProgram: TAccountMetas[11];
  };
  data: IncreaseVoteBuyInstructionData;
}

export function parseIncreaseVoteBuyInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedIncreaseVoteBuyInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 12) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      buyer: getNextAccount(),
      buyerTokenAccount: getNextAccount(),
      tokenVault: getNextAccount(),
      mint: getNextAccount(),
      config: getNextAccount(),
      gaugemeister: getNextAccount(),
      voteBuy: getNextAccount(),
      gauge: getNextAccount(),
      allowedMints: getNextAccount(),
      tokenProgram: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getIncreaseVoteBuyInstructionDataDecoder().decode(instruction.data),
  };
}
