/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import type {
  AccountMeta,
  AccountSignerMeta,
  Address,
  FixedSizeCodec,
  FixedSizeDecoder,
  FixedSizeEncoder,
  Instruction,
  InstructionWithAccounts,
  InstructionWithData,
  ReadonlyAccount,
  ReadonlySignerAccount,
  ReadonlyUint8Array,
  TransactionSigner,
  WritableAccount,
} from "@solana/kit";
import type { ResolvedAccount } from "../shared/index.js";
import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
} from "@solana/kit";
import { VOTE_MARKET_PROGRAM_ADDRESS } from "../programs/index.js";
import { getAccountMetaFactory } from "../shared/index.js";

export const SET_MAX_AMOUNT_DISCRIMINATOR = new Uint8Array([
  226, 133, 252, 54, 185, 15, 122, 154,
]);

export function getSetMaxAmountDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SET_MAX_AMOUNT_DISCRIMINATOR,
  );
}

export type SetMaxAmountInstruction<
  TProgram extends string = typeof VOTE_MARKET_PROGRAM_ADDRESS,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountVoteBuy extends string | AccountMeta<string> = string,
  TAccountGauge extends string | AccountMeta<string> = string,
  TAccountScriptAuthority extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountVoteBuy extends string
        ? WritableAccount<TAccountVoteBuy>
        : TAccountVoteBuy,
      TAccountGauge extends string
        ? ReadonlyAccount<TAccountGauge>
        : TAccountGauge,
      TAccountScriptAuthority extends string
        ? ReadonlySignerAccount<TAccountScriptAuthority> &
            AccountSignerMeta<TAccountScriptAuthority>
        : TAccountScriptAuthority,
      ...TRemainingAccounts,
    ]
  >;

export interface SetMaxAmountInstructionData {
  discriminator: ReadonlyUint8Array;
  epoch: number;
  maxAmount: bigint;
}

export interface SetMaxAmountInstructionDataArgs {
  epoch: number;
  maxAmount: number | bigint;
}

export function getSetMaxAmountInstructionDataEncoder(): FixedSizeEncoder<SetMaxAmountInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["epoch", getU32Encoder()],
      ["maxAmount", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: SET_MAX_AMOUNT_DISCRIMINATOR }),
  );
}

export function getSetMaxAmountInstructionDataDecoder(): FixedSizeDecoder<SetMaxAmountInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["epoch", getU32Decoder()],
    ["maxAmount", getU64Decoder()],
  ]);
}

export function getSetMaxAmountInstructionDataCodec(): FixedSizeCodec<
  SetMaxAmountInstructionDataArgs,
  SetMaxAmountInstructionData
> {
  return combineCodec(
    getSetMaxAmountInstructionDataEncoder(),
    getSetMaxAmountInstructionDataDecoder(),
  );
}

export interface SetMaxAmountInput<
  TAccountConfig extends string = string,
  TAccountVoteBuy extends string = string,
  TAccountGauge extends string = string,
  TAccountScriptAuthority extends string = string,
> {
  config: Address<TAccountConfig>;
  voteBuy: Address<TAccountVoteBuy>;
  gauge: Address<TAccountGauge>;
  scriptAuthority: TransactionSigner<TAccountScriptAuthority>;
  epoch: SetMaxAmountInstructionDataArgs["epoch"];
  maxAmount: SetMaxAmountInstructionDataArgs["maxAmount"];
}

export function getSetMaxAmountInstruction<
  TAccountConfig extends string,
  TAccountVoteBuy extends string,
  TAccountGauge extends string,
  TAccountScriptAuthority extends string,
  TProgramAddress extends Address = typeof VOTE_MARKET_PROGRAM_ADDRESS,
>(
  input: SetMaxAmountInput<
    TAccountConfig,
    TAccountVoteBuy,
    TAccountGauge,
    TAccountScriptAuthority
  >,
  config?: { programAddress?: TProgramAddress },
): SetMaxAmountInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountVoteBuy,
  TAccountGauge,
  TAccountScriptAuthority
> {
  // Program address.
  const programAddress = config?.programAddress ?? VOTE_MARKET_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: false },
    voteBuy: { value: input.voteBuy ?? null, isWritable: true },
    gauge: { value: input.gauge ?? null, isWritable: false },
    scriptAuthority: {
      value: input.scriptAuthority ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.voteBuy),
      getAccountMeta(accounts.gauge),
      getAccountMeta(accounts.scriptAuthority),
    ],
    data: getSetMaxAmountInstructionDataEncoder().encode(
      args as SetMaxAmountInstructionDataArgs,
    ),
    programAddress,
  } as SetMaxAmountInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountVoteBuy,
    TAccountGauge,
    TAccountScriptAuthority
  >);
}

export interface ParsedSetMaxAmountInstruction<
  TProgram extends string = typeof VOTE_MARKET_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> {
  programAddress: Address<TProgram>;
  accounts: {
    config: TAccountMetas[0];
    voteBuy: TAccountMetas[1];
    gauge: TAccountMetas[2];
    scriptAuthority: TAccountMetas[3];
  };
  data: SetMaxAmountInstructionData;
}

export function parseSetMaxAmountInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedSetMaxAmountInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      voteBuy: getNextAccount(),
      gauge: getNextAccount(),
      scriptAuthority: getNextAccount(),
    },
    data: getSetMaxAmountInstructionDataDecoder().decode(instruction.data),
  };
}
