/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import type {
  AccountMeta,
  AccountSignerMeta,
  Address,
  Codec,
  Decoder,
  Encoder,
  Instruction,
  InstructionWithAccounts,
  InstructionWithData,
  ReadonlyAccount,
  ReadonlyUint8Array,
  TransactionSigner,
  WritableAccount,
  WritableSignerAccount,
} from "@solana/kit";
import type { ResolvedAccount } from "../shared/index.js";
import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
} from "@solana/kit";
import { VOTE_MARKET_PROGRAM_ADDRESS } from "../programs/index.js";
import { getAccountMetaFactory } from "../shared/index.js";

export const UPDATE_ALLOWED_MINTS_DISCRIMINATOR = new Uint8Array([
  146, 211, 161, 2, 10, 20, 94, 67,
]);

export function getUpdateAllowedMintsDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_ALLOWED_MINTS_DISCRIMINATOR,
  );
}

export type UpdateAllowedMintsInstruction<
  TProgram extends string = typeof VOTE_MARKET_PROGRAM_ADDRESS,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountAllowedMints extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountAllowedMints extends string
        ? WritableAccount<TAccountAllowedMints>
        : TAccountAllowedMints,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export interface UpdateAllowedMintsInstructionData {
  discriminator: ReadonlyUint8Array;
  allowedMints: Address[];
}

export interface UpdateAllowedMintsInstructionDataArgs {
  allowedMints: Address[];
}

export function getUpdateAllowedMintsInstructionDataEncoder(): Encoder<UpdateAllowedMintsInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["allowedMints", getArrayEncoder(getAddressEncoder())],
    ]),
    (value) => ({
      ...value,
      discriminator: UPDATE_ALLOWED_MINTS_DISCRIMINATOR,
    }),
  );
}

export function getUpdateAllowedMintsInstructionDataDecoder(): Decoder<UpdateAllowedMintsInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["allowedMints", getArrayDecoder(getAddressDecoder())],
  ]);
}

export function getUpdateAllowedMintsInstructionDataCodec(): Codec<
  UpdateAllowedMintsInstructionDataArgs,
  UpdateAllowedMintsInstructionData
> {
  return combineCodec(
    getUpdateAllowedMintsInstructionDataEncoder(),
    getUpdateAllowedMintsInstructionDataDecoder(),
  );
}

export interface UpdateAllowedMintsInput<
  TAccountConfig extends string = string,
  TAccountAdmin extends string = string,
  TAccountAllowedMints extends string = string,
  TAccountSystemProgram extends string = string,
> {
  config: Address<TAccountConfig>;
  admin: TransactionSigner<TAccountAdmin>;
  allowedMints: Address<TAccountAllowedMints>;
  systemProgram?: Address<TAccountSystemProgram>;
  allowedMintsArg: UpdateAllowedMintsInstructionDataArgs["allowedMints"];
}

export function getUpdateAllowedMintsInstruction<
  TAccountConfig extends string,
  TAccountAdmin extends string,
  TAccountAllowedMints extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof VOTE_MARKET_PROGRAM_ADDRESS,
>(
  input: UpdateAllowedMintsInput<
    TAccountConfig,
    TAccountAdmin,
    TAccountAllowedMints,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): UpdateAllowedMintsInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountAdmin,
  TAccountAllowedMints,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? VOTE_MARKET_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: true },
    admin: { value: input.admin ?? null, isWritable: true },
    allowedMints: { value: input.allowedMints ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input, allowedMints: input.allowedMintsArg };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.allowedMints),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getUpdateAllowedMintsInstructionDataEncoder().encode(
      args as UpdateAllowedMintsInstructionDataArgs,
    ),
    programAddress,
  } as UpdateAllowedMintsInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountAdmin,
    TAccountAllowedMints,
    TAccountSystemProgram
  >);
}

export interface ParsedUpdateAllowedMintsInstruction<
  TProgram extends string = typeof VOTE_MARKET_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> {
  programAddress: Address<TProgram>;
  accounts: {
    config: TAccountMetas[0];
    admin: TAccountMetas[1];
    allowedMints: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
  };
  data: UpdateAllowedMintsInstructionData;
}

export function parseUpdateAllowedMintsInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedUpdateAllowedMintsInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      admin: getNextAccount(),
      allowedMints: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getUpdateAllowedMintsInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
