/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import type {
  AccountMeta,
  AccountSignerMeta,
  Address,
  FixedSizeCodec,
  FixedSizeDecoder,
  FixedSizeEncoder,
  Instruction,
  InstructionWithAccounts,
  InstructionWithData,
  ReadonlyAccount,
  ReadonlyUint8Array,
  TransactionSigner,
  WritableAccount,
  WritableSignerAccount,
} from "@solana/kit";
import type { ResolvedAccount } from "../shared/index.js";
import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
} from "@solana/kit";
import { VOTE_MARKET_PROGRAM_ADDRESS } from "../programs/index.js";
import { getAccountMetaFactory } from "../shared/index.js";

export const UPDATE_REWARD_ACCUMULATOR_CONFIG_DISCRIMINATOR = new Uint8Array([
  212, 118, 126, 80, 89, 132, 184, 215,
]);

export function getUpdateRewardAccumulatorConfigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_REWARD_ACCUMULATOR_CONFIG_DISCRIMINATOR,
  );
}

export type UpdateRewardAccumulatorConfigInstruction<
  TProgram extends string = typeof VOTE_MARKET_PROGRAM_ADDRESS,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountRewardAccumulatorConfig extends string | AccountMeta<string> = string,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountRewardAccumulatorConfig extends string
        ? WritableAccount<TAccountRewardAccumulatorConfig>
        : TAccountRewardAccumulatorConfig,
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export interface UpdateRewardAccumulatorConfigInstructionData {
  discriminator: ReadonlyUint8Array;
  rewardAccumulatorProgram: Address;
  namespace: ReadonlyUint8Array;
}

export interface UpdateRewardAccumulatorConfigInstructionDataArgs {
  rewardAccumulatorProgram: Address;
  namespace: ReadonlyUint8Array;
}

export function getUpdateRewardAccumulatorConfigInstructionDataEncoder(): FixedSizeEncoder<UpdateRewardAccumulatorConfigInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["rewardAccumulatorProgram", getAddressEncoder()],
      ["namespace", fixEncoderSize(getBytesEncoder(), 8)],
    ]),
    (value) => ({
      ...value,
      discriminator: UPDATE_REWARD_ACCUMULATOR_CONFIG_DISCRIMINATOR,
    }),
  );
}

export function getUpdateRewardAccumulatorConfigInstructionDataDecoder(): FixedSizeDecoder<UpdateRewardAccumulatorConfigInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["rewardAccumulatorProgram", getAddressDecoder()],
    ["namespace", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getUpdateRewardAccumulatorConfigInstructionDataCodec(): FixedSizeCodec<
  UpdateRewardAccumulatorConfigInstructionDataArgs,
  UpdateRewardAccumulatorConfigInstructionData
> {
  return combineCodec(
    getUpdateRewardAccumulatorConfigInstructionDataEncoder(),
    getUpdateRewardAccumulatorConfigInstructionDataDecoder(),
  );
}

export interface UpdateRewardAccumulatorConfigInput<
  TAccountConfig extends string = string,
  TAccountRewardAccumulatorConfig extends string = string,
  TAccountAdmin extends string = string,
  TAccountSystemProgram extends string = string,
> {
  config: Address<TAccountConfig>;
  rewardAccumulatorConfig: Address<TAccountRewardAccumulatorConfig>;
  admin: TransactionSigner<TAccountAdmin>;
  systemProgram?: Address<TAccountSystemProgram>;
  rewardAccumulatorProgram: UpdateRewardAccumulatorConfigInstructionDataArgs["rewardAccumulatorProgram"];
  namespace: UpdateRewardAccumulatorConfigInstructionDataArgs["namespace"];
}

export function getUpdateRewardAccumulatorConfigInstruction<
  TAccountConfig extends string,
  TAccountRewardAccumulatorConfig extends string,
  TAccountAdmin extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof VOTE_MARKET_PROGRAM_ADDRESS,
>(
  input: UpdateRewardAccumulatorConfigInput<
    TAccountConfig,
    TAccountRewardAccumulatorConfig,
    TAccountAdmin,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): UpdateRewardAccumulatorConfigInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountRewardAccumulatorConfig,
  TAccountAdmin,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? VOTE_MARKET_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: false },
    rewardAccumulatorConfig: {
      value: input.rewardAccumulatorConfig ?? null,
      isWritable: true,
    },
    admin: { value: input.admin ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.rewardAccumulatorConfig),
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getUpdateRewardAccumulatorConfigInstructionDataEncoder().encode(
      args as UpdateRewardAccumulatorConfigInstructionDataArgs,
    ),
    programAddress,
  } as UpdateRewardAccumulatorConfigInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountRewardAccumulatorConfig,
    TAccountAdmin,
    TAccountSystemProgram
  >);
}

export interface ParsedUpdateRewardAccumulatorConfigInstruction<
  TProgram extends string = typeof VOTE_MARKET_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> {
  programAddress: Address<TProgram>;
  accounts: {
    config: TAccountMetas[0];
    rewardAccumulatorConfig: TAccountMetas[1];
    admin: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
  };
  data: UpdateRewardAccumulatorConfigInstructionData;
}

export function parseUpdateRewardAccumulatorConfigInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedUpdateRewardAccumulatorConfigInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      rewardAccumulatorConfig: getNextAccount(),
      admin: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getUpdateRewardAccumulatorConfigInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
