/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import type {
  AccountMeta,
  AccountSignerMeta,
  Address,
  FixedSizeCodec,
  FixedSizeDecoder,
  FixedSizeEncoder,
  Instruction,
  InstructionWithAccounts,
  InstructionWithData,
  ReadonlySignerAccount,
  ReadonlyUint8Array,
  TransactionSigner,
  WritableAccount,
} from "@solana/kit";
import type { ResolvedAccount } from "../shared/index.js";
import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  transformEncoder,
} from "@solana/kit";
import { VOTE_MARKET_PROGRAM_ADDRESS } from "../programs/index.js";
import { getAccountMetaFactory } from "../shared/index.js";

export const UPDATE_CLAIM_FEE_DISCRIMINATOR = new Uint8Array([
  192, 255, 140, 184, 150, 96, 181, 103,
]);

export function getUpdateClaimFeeDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_CLAIM_FEE_DISCRIMINATOR,
  );
}

export type UpdateClaimFeeInstruction<
  TProgram extends string = typeof VOTE_MARKET_PROGRAM_ADDRESS,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      TAccountAdmin extends string
        ? ReadonlySignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      ...TRemainingAccounts,
    ]
  >;

export interface UpdateClaimFeeInstructionData {
  discriminator: ReadonlyUint8Array;
  claimFee: number;
}

export interface UpdateClaimFeeInstructionDataArgs {
  claimFee: number;
}

export function getUpdateClaimFeeInstructionDataEncoder(): FixedSizeEncoder<UpdateClaimFeeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["claimFee", getU16Encoder()],
    ]),
    (value) => ({ ...value, discriminator: UPDATE_CLAIM_FEE_DISCRIMINATOR }),
  );
}

export function getUpdateClaimFeeInstructionDataDecoder(): FixedSizeDecoder<UpdateClaimFeeInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["claimFee", getU16Decoder()],
  ]);
}

export function getUpdateClaimFeeInstructionDataCodec(): FixedSizeCodec<
  UpdateClaimFeeInstructionDataArgs,
  UpdateClaimFeeInstructionData
> {
  return combineCodec(
    getUpdateClaimFeeInstructionDataEncoder(),
    getUpdateClaimFeeInstructionDataDecoder(),
  );
}

export interface UpdateClaimFeeInput<
  TAccountConfig extends string = string,
  TAccountAdmin extends string = string,
> {
  config: Address<TAccountConfig>;
  admin: TransactionSigner<TAccountAdmin>;
  claimFee: UpdateClaimFeeInstructionDataArgs["claimFee"];
}

export function getUpdateClaimFeeInstruction<
  TAccountConfig extends string,
  TAccountAdmin extends string,
  TProgramAddress extends Address = typeof VOTE_MARKET_PROGRAM_ADDRESS,
>(
  input: UpdateClaimFeeInput<TAccountConfig, TAccountAdmin>,
  config?: { programAddress?: TProgramAddress },
): UpdateClaimFeeInstruction<TProgramAddress, TAccountConfig, TAccountAdmin> {
  // Program address.
  const programAddress = config?.programAddress ?? VOTE_MARKET_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: true },
    admin: { value: input.admin ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [getAccountMeta(accounts.config), getAccountMeta(accounts.admin)],
    data: getUpdateClaimFeeInstructionDataEncoder().encode(
      args as UpdateClaimFeeInstructionDataArgs,
    ),
    programAddress,
  } as UpdateClaimFeeInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountAdmin
  >);
}

export interface ParsedUpdateClaimFeeInstruction<
  TProgram extends string = typeof VOTE_MARKET_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> {
  programAddress: Address<TProgram>;
  accounts: {
    config: TAccountMetas[0];
    admin: TAccountMetas[1];
  };
  data: UpdateClaimFeeInstructionData;
}

export function parseUpdateClaimFeeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedUpdateClaimFeeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { config: getNextAccount(), admin: getNextAccount() },
    data: getUpdateClaimFeeInstructionDataDecoder().decode(instruction.data),
  };
}
