/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import type {
  AccountMeta,
  AccountSignerMeta,
  Address,
  FixedSizeCodec,
  FixedSizeDecoder,
  FixedSizeEncoder,
  Instruction,
  InstructionWithAccounts,
  InstructionWithData,
  ReadonlySignerAccount,
  ReadonlyUint8Array,
  TransactionSigner,
  WritableAccount,
} from "@solana/kit";
import type { ResolvedAccount } from "../shared/index.js";
import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
} from "@solana/kit";
import { VOTE_MARKET_PROGRAM_ADDRESS } from "../programs/index.js";
import { getAccountMetaFactory } from "../shared/index.js";

export const UPDATE_SCRIPT_AUTHORITY_DISCRIMINATOR = new Uint8Array([
  57, 237, 52, 47, 112, 6, 101, 72,
]);

export function getUpdateScriptAuthorityDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_SCRIPT_AUTHORITY_DISCRIMINATOR,
  );
}

export type UpdateScriptAuthorityInstruction<
  TProgram extends string = typeof VOTE_MARKET_PROGRAM_ADDRESS,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      TAccountAdmin extends string
        ? ReadonlySignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      ...TRemainingAccounts,
    ]
  >;

export interface UpdateScriptAuthorityInstructionData {
  discriminator: ReadonlyUint8Array;
  scriptAuthority: Address;
}

export interface UpdateScriptAuthorityInstructionDataArgs {
  scriptAuthority: Address;
}

export function getUpdateScriptAuthorityInstructionDataEncoder(): FixedSizeEncoder<UpdateScriptAuthorityInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["scriptAuthority", getAddressEncoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: UPDATE_SCRIPT_AUTHORITY_DISCRIMINATOR,
    }),
  );
}

export function getUpdateScriptAuthorityInstructionDataDecoder(): FixedSizeDecoder<UpdateScriptAuthorityInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["scriptAuthority", getAddressDecoder()],
  ]);
}

export function getUpdateScriptAuthorityInstructionDataCodec(): FixedSizeCodec<
  UpdateScriptAuthorityInstructionDataArgs,
  UpdateScriptAuthorityInstructionData
> {
  return combineCodec(
    getUpdateScriptAuthorityInstructionDataEncoder(),
    getUpdateScriptAuthorityInstructionDataDecoder(),
  );
}

export interface UpdateScriptAuthorityInput<
  TAccountConfig extends string = string,
  TAccountAdmin extends string = string,
> {
  config: Address<TAccountConfig>;
  admin: TransactionSigner<TAccountAdmin>;
  scriptAuthority: UpdateScriptAuthorityInstructionDataArgs["scriptAuthority"];
}

export function getUpdateScriptAuthorityInstruction<
  TAccountConfig extends string,
  TAccountAdmin extends string,
  TProgramAddress extends Address = typeof VOTE_MARKET_PROGRAM_ADDRESS,
>(
  input: UpdateScriptAuthorityInput<TAccountConfig, TAccountAdmin>,
  config?: { programAddress?: TProgramAddress },
): UpdateScriptAuthorityInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountAdmin
> {
  // Program address.
  const programAddress = config?.programAddress ?? VOTE_MARKET_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: true },
    admin: { value: input.admin ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [getAccountMeta(accounts.config), getAccountMeta(accounts.admin)],
    data: getUpdateScriptAuthorityInstructionDataEncoder().encode(
      args as UpdateScriptAuthorityInstructionDataArgs,
    ),
    programAddress,
  } as UpdateScriptAuthorityInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountAdmin
  >);
}

export interface ParsedUpdateScriptAuthorityInstruction<
  TProgram extends string = typeof VOTE_MARKET_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> {
  programAddress: Address<TProgram>;
  accounts: {
    config: TAccountMetas[0];
    admin: TAccountMetas[1];
  };
  data: UpdateScriptAuthorityInstructionData;
}

export function parseUpdateScriptAuthorityInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedUpdateScriptAuthorityInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { config: getNextAccount(), admin: getNextAccount() },
    data: getUpdateScriptAuthorityInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
