/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import type {
  AccountMeta,
  AccountSignerMeta,
  Address,
  FixedSizeCodec,
  FixedSizeDecoder,
  FixedSizeEncoder,
  Instruction,
  InstructionWithAccounts,
  InstructionWithData,
  ReadonlyAccount,
  ReadonlySignerAccount,
  ReadonlyUint8Array,
  TransactionSigner,
  WritableAccount,
} from "@solana/kit";
import type { ResolvedAccount } from "../shared/index.js";
import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  transformEncoder,
} from "@solana/kit";
import { VOTE_MARKET_PROGRAM_ADDRESS } from "../programs/index.js";
import { getAccountMetaFactory } from "../shared/index.js";

export const VOTE_DISCRIMINATOR = new Uint8Array([
  227, 110, 155, 23, 136, 126, 172, 25,
]);

export function getVoteDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(VOTE_DISCRIMINATOR);
}

export type VoteInstruction<
  TProgram extends string = typeof VOTE_MARKET_PROGRAM_ADDRESS,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountScriptAuthority extends string | AccountMeta<string> = string,
  TAccountGaugemeister extends string | AccountMeta<string> = string,
  TAccountGauge extends string | AccountMeta<string> = string,
  TAccountGaugeVoter extends string | AccountMeta<string> = string,
  TAccountGaugeVote extends string | AccountMeta<string> = string,
  TAccountEscrow extends string | AccountMeta<string> = string,
  TAccountVoteDelegate extends string | AccountMeta<string> = string,
  TAccountGaugeProgram extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountScriptAuthority extends string
        ? ReadonlySignerAccount<TAccountScriptAuthority> &
            AccountSignerMeta<TAccountScriptAuthority>
        : TAccountScriptAuthority,
      TAccountGaugemeister extends string
        ? ReadonlyAccount<TAccountGaugemeister>
        : TAccountGaugemeister,
      TAccountGauge extends string
        ? ReadonlyAccount<TAccountGauge>
        : TAccountGauge,
      TAccountGaugeVoter extends string
        ? WritableAccount<TAccountGaugeVoter>
        : TAccountGaugeVoter,
      TAccountGaugeVote extends string
        ? WritableAccount<TAccountGaugeVote>
        : TAccountGaugeVote,
      TAccountEscrow extends string
        ? ReadonlyAccount<TAccountEscrow>
        : TAccountEscrow,
      TAccountVoteDelegate extends string
        ? WritableAccount<TAccountVoteDelegate>
        : TAccountVoteDelegate,
      TAccountGaugeProgram extends string
        ? ReadonlyAccount<TAccountGaugeProgram>
        : TAccountGaugeProgram,
      ...TRemainingAccounts,
    ]
  >;

export interface VoteInstructionData {
  discriminator: ReadonlyUint8Array;
  weight: number;
}

export interface VoteInstructionDataArgs {
  weight: number;
}

export function getVoteInstructionDataEncoder(): FixedSizeEncoder<VoteInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["weight", getU32Encoder()],
    ]),
    (value) => ({ ...value, discriminator: VOTE_DISCRIMINATOR }),
  );
}

export function getVoteInstructionDataDecoder(): FixedSizeDecoder<VoteInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["weight", getU32Decoder()],
  ]);
}

export function getVoteInstructionDataCodec(): FixedSizeCodec<
  VoteInstructionDataArgs,
  VoteInstructionData
> {
  return combineCodec(
    getVoteInstructionDataEncoder(),
    getVoteInstructionDataDecoder(),
  );
}

export interface VoteInput<
  TAccountConfig extends string = string,
  TAccountScriptAuthority extends string = string,
  TAccountGaugemeister extends string = string,
  TAccountGauge extends string = string,
  TAccountGaugeVoter extends string = string,
  TAccountGaugeVote extends string = string,
  TAccountEscrow extends string = string,
  TAccountVoteDelegate extends string = string,
  TAccountGaugeProgram extends string = string,
> {
  config: Address<TAccountConfig>;
  scriptAuthority: TransactionSigner<TAccountScriptAuthority>;
  gaugemeister: Address<TAccountGaugemeister>;
  gauge: Address<TAccountGauge>;
  gaugeVoter: Address<TAccountGaugeVoter>;
  gaugeVote: Address<TAccountGaugeVote>;
  escrow: Address<TAccountEscrow>;
  voteDelegate: Address<TAccountVoteDelegate>;
  gaugeProgram: Address<TAccountGaugeProgram>;
  weight: VoteInstructionDataArgs["weight"];
}

export function getVoteInstruction<
  TAccountConfig extends string,
  TAccountScriptAuthority extends string,
  TAccountGaugemeister extends string,
  TAccountGauge extends string,
  TAccountGaugeVoter extends string,
  TAccountGaugeVote extends string,
  TAccountEscrow extends string,
  TAccountVoteDelegate extends string,
  TAccountGaugeProgram extends string,
  TProgramAddress extends Address = typeof VOTE_MARKET_PROGRAM_ADDRESS,
>(
  input: VoteInput<
    TAccountConfig,
    TAccountScriptAuthority,
    TAccountGaugemeister,
    TAccountGauge,
    TAccountGaugeVoter,
    TAccountGaugeVote,
    TAccountEscrow,
    TAccountVoteDelegate,
    TAccountGaugeProgram
  >,
  config?: { programAddress?: TProgramAddress },
): VoteInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountScriptAuthority,
  TAccountGaugemeister,
  TAccountGauge,
  TAccountGaugeVoter,
  TAccountGaugeVote,
  TAccountEscrow,
  TAccountVoteDelegate,
  TAccountGaugeProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? VOTE_MARKET_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: false },
    scriptAuthority: {
      value: input.scriptAuthority ?? null,
      isWritable: false,
    },
    gaugemeister: { value: input.gaugemeister ?? null, isWritable: false },
    gauge: { value: input.gauge ?? null, isWritable: false },
    gaugeVoter: { value: input.gaugeVoter ?? null, isWritable: true },
    gaugeVote: { value: input.gaugeVote ?? null, isWritable: true },
    escrow: { value: input.escrow ?? null, isWritable: false },
    voteDelegate: { value: input.voteDelegate ?? null, isWritable: true },
    gaugeProgram: { value: input.gaugeProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.scriptAuthority),
      getAccountMeta(accounts.gaugemeister),
      getAccountMeta(accounts.gauge),
      getAccountMeta(accounts.gaugeVoter),
      getAccountMeta(accounts.gaugeVote),
      getAccountMeta(accounts.escrow),
      getAccountMeta(accounts.voteDelegate),
      getAccountMeta(accounts.gaugeProgram),
    ],
    data: getVoteInstructionDataEncoder().encode(
      args as VoteInstructionDataArgs,
    ),
    programAddress,
  } as VoteInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountScriptAuthority,
    TAccountGaugemeister,
    TAccountGauge,
    TAccountGaugeVoter,
    TAccountGaugeVote,
    TAccountEscrow,
    TAccountVoteDelegate,
    TAccountGaugeProgram
  >);
}

export interface ParsedVoteInstruction<
  TProgram extends string = typeof VOTE_MARKET_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> {
  programAddress: Address<TProgram>;
  accounts: {
    config: TAccountMetas[0];
    scriptAuthority: TAccountMetas[1];
    gaugemeister: TAccountMetas[2];
    gauge: TAccountMetas[3];
    gaugeVoter: TAccountMetas[4];
    gaugeVote: TAccountMetas[5];
    escrow: TAccountMetas[6];
    voteDelegate: TAccountMetas[7];
    gaugeProgram: TAccountMetas[8];
  };
  data: VoteInstructionData;
}

export function parseVoteInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedVoteInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 9) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      scriptAuthority: getNextAccount(),
      gaugemeister: getNextAccount(),
      gauge: getNextAccount(),
      gaugeVoter: getNextAccount(),
      gaugeVote: getNextAccount(),
      escrow: getNextAccount(),
      voteDelegate: getNextAccount(),
      gaugeProgram: getNextAccount(),
    },
    data: getVoteInstructionDataDecoder().decode(instruction.data),
  };
}
