/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import type {
  AccountMeta,
  AccountSignerMeta,
  Address,
  FixedSizeCodec,
  FixedSizeDecoder,
  FixedSizeEncoder,
  Instruction,
  InstructionWithAccounts,
  InstructionWithData,
  ReadonlyAccount,
  ReadonlySignerAccount,
  ReadonlyUint8Array,
  TransactionSigner,
  WritableAccount,
} from "@solana/kit";
import type { ResolvedAccount } from "../shared/index.js";
import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  transformEncoder,
} from "@solana/kit";
import { VOTE_MARKET_PROGRAM_ADDRESS } from "../programs/index.js";
import { getAccountMetaFactory } from "../shared/index.js";

export const VOTE_BUY_REFUND_DISCRIMINATOR = new Uint8Array([
  178, 215, 141, 180, 246, 105, 86, 32,
]);

export function getVoteBuyRefundDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    VOTE_BUY_REFUND_DISCRIMINATOR,
  );
}

export type VoteBuyRefundInstruction<
  TProgram extends string = typeof VOTE_MARKET_PROGRAM_ADDRESS,
  TAccountBuyer extends string | AccountMeta<string> = string,
  TAccountBuyerTokenAccount extends string | AccountMeta<string> = string,
  TAccountTokenVault extends string | AccountMeta<string> = string,
  TAccountVoteBuy extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountGauge extends string | AccountMeta<string> = string,
  TAccountGaugemeister extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountBuyer extends string
        ? ReadonlySignerAccount<TAccountBuyer> &
            AccountSignerMeta<TAccountBuyer>
        : TAccountBuyer,
      TAccountBuyerTokenAccount extends string
        ? WritableAccount<TAccountBuyerTokenAccount>
        : TAccountBuyerTokenAccount,
      TAccountTokenVault extends string
        ? WritableAccount<TAccountTokenVault>
        : TAccountTokenVault,
      TAccountVoteBuy extends string
        ? WritableAccount<TAccountVoteBuy>
        : TAccountVoteBuy,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountGauge extends string
        ? ReadonlyAccount<TAccountGauge>
        : TAccountGauge,
      TAccountGaugemeister extends string
        ? ReadonlyAccount<TAccountGaugemeister>
        : TAccountGaugemeister,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export interface VoteBuyRefundInstructionData {
  discriminator: ReadonlyUint8Array;
  epoch: number;
}

export interface VoteBuyRefundInstructionDataArgs {
  epoch: number;
}

export function getVoteBuyRefundInstructionDataEncoder(): FixedSizeEncoder<VoteBuyRefundInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["epoch", getU32Encoder()],
    ]),
    (value) => ({ ...value, discriminator: VOTE_BUY_REFUND_DISCRIMINATOR }),
  );
}

export function getVoteBuyRefundInstructionDataDecoder(): FixedSizeDecoder<VoteBuyRefundInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["epoch", getU32Decoder()],
  ]);
}

export function getVoteBuyRefundInstructionDataCodec(): FixedSizeCodec<
  VoteBuyRefundInstructionDataArgs,
  VoteBuyRefundInstructionData
> {
  return combineCodec(
    getVoteBuyRefundInstructionDataEncoder(),
    getVoteBuyRefundInstructionDataDecoder(),
  );
}

export interface VoteBuyRefundInput<
  TAccountBuyer extends string = string,
  TAccountBuyerTokenAccount extends string = string,
  TAccountTokenVault extends string = string,
  TAccountVoteBuy extends string = string,
  TAccountMint extends string = string,
  TAccountConfig extends string = string,
  TAccountGauge extends string = string,
  TAccountGaugemeister extends string = string,
  TAccountTokenProgram extends string = string,
> {
  buyer: TransactionSigner<TAccountBuyer>;
  buyerTokenAccount: Address<TAccountBuyerTokenAccount>;
  tokenVault: Address<TAccountTokenVault>;
  voteBuy: Address<TAccountVoteBuy>;
  mint: Address<TAccountMint>;
  config: Address<TAccountConfig>;
  gauge: Address<TAccountGauge>;
  gaugemeister: Address<TAccountGaugemeister>;
  tokenProgram?: Address<TAccountTokenProgram>;
  epoch: VoteBuyRefundInstructionDataArgs["epoch"];
}

export function getVoteBuyRefundInstruction<
  TAccountBuyer extends string,
  TAccountBuyerTokenAccount extends string,
  TAccountTokenVault extends string,
  TAccountVoteBuy extends string,
  TAccountMint extends string,
  TAccountConfig extends string,
  TAccountGauge extends string,
  TAccountGaugemeister extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof VOTE_MARKET_PROGRAM_ADDRESS,
>(
  input: VoteBuyRefundInput<
    TAccountBuyer,
    TAccountBuyerTokenAccount,
    TAccountTokenVault,
    TAccountVoteBuy,
    TAccountMint,
    TAccountConfig,
    TAccountGauge,
    TAccountGaugemeister,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): VoteBuyRefundInstruction<
  TProgramAddress,
  TAccountBuyer,
  TAccountBuyerTokenAccount,
  TAccountTokenVault,
  TAccountVoteBuy,
  TAccountMint,
  TAccountConfig,
  TAccountGauge,
  TAccountGaugemeister,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? VOTE_MARKET_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    buyer: { value: input.buyer ?? null, isWritable: false },
    buyerTokenAccount: {
      value: input.buyerTokenAccount ?? null,
      isWritable: true,
    },
    tokenVault: { value: input.tokenVault ?? null, isWritable: true },
    voteBuy: { value: input.voteBuy ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: false },
    gauge: { value: input.gauge ?? null, isWritable: false },
    gaugemeister: { value: input.gaugemeister ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.buyer),
      getAccountMeta(accounts.buyerTokenAccount),
      getAccountMeta(accounts.tokenVault),
      getAccountMeta(accounts.voteBuy),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.gauge),
      getAccountMeta(accounts.gaugemeister),
      getAccountMeta(accounts.tokenProgram),
    ],
    data: getVoteBuyRefundInstructionDataEncoder().encode(
      args as VoteBuyRefundInstructionDataArgs,
    ),
    programAddress,
  } as VoteBuyRefundInstruction<
    TProgramAddress,
    TAccountBuyer,
    TAccountBuyerTokenAccount,
    TAccountTokenVault,
    TAccountVoteBuy,
    TAccountMint,
    TAccountConfig,
    TAccountGauge,
    TAccountGaugemeister,
    TAccountTokenProgram
  >);
}

export interface ParsedVoteBuyRefundInstruction<
  TProgram extends string = typeof VOTE_MARKET_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> {
  programAddress: Address<TProgram>;
  accounts: {
    buyer: TAccountMetas[0];
    buyerTokenAccount: TAccountMetas[1];
    tokenVault: TAccountMetas[2];
    voteBuy: TAccountMetas[3];
    mint: TAccountMetas[4];
    config: TAccountMetas[5];
    gauge: TAccountMetas[6];
    gaugemeister: TAccountMetas[7];
    tokenProgram: TAccountMetas[8];
  };
  data: VoteBuyRefundInstructionData;
}

export function parseVoteBuyRefundInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedVoteBuyRefundInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 9) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      buyer: getNextAccount(),
      buyerTokenAccount: getNextAccount(),
      tokenVault: getNextAccount(),
      voteBuy: getNextAccount(),
      mint: getNextAccount(),
      config: getNextAccount(),
      gauge: getNextAccount(),
      gaugemeister: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getVoteBuyRefundInstructionDataDecoder().decode(instruction.data),
  };
}
