/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import type {
  Account,
  Address,
  Codec,
  Decoder,
  EncodedAccount,
  Encoder,
  FetchAccountConfig,
  FetchAccountsConfig,
  MaybeAccount,
  MaybeEncodedAccount,
  ReadonlyUint8Array,
} from "@solana/kit";
import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
} from "@solana/kit";

export const ALLOWED_MINTS_DISCRIMINATOR = new Uint8Array([
  207, 250, 95, 68, 245, 220, 110, 31,
]);

export function getAllowedMintsDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    ALLOWED_MINTS_DISCRIMINATOR,
  );
}

export interface AllowedMints {
  discriminator: ReadonlyUint8Array;
  mints: Address[];
}

export interface AllowedMintsArgs {
  mints: Address[];
}

export function getAllowedMintsEncoder(): Encoder<AllowedMintsArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["mints", getArrayEncoder(getAddressEncoder())],
    ]),
    (value) => ({ ...value, discriminator: ALLOWED_MINTS_DISCRIMINATOR }),
  );
}

export function getAllowedMintsDecoder(): Decoder<AllowedMints> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["mints", getArrayDecoder(getAddressDecoder())],
  ]);
}

export function getAllowedMintsCodec(): Codec<AllowedMintsArgs, AllowedMints> {
  return combineCodec(getAllowedMintsEncoder(), getAllowedMintsDecoder());
}

export function decodeAllowedMints<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<AllowedMints, TAddress>;
export function decodeAllowedMints<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<AllowedMints, TAddress>;
export function decodeAllowedMints<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<AllowedMints, TAddress> | MaybeAccount<AllowedMints, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getAllowedMintsDecoder(),
  );
}

export async function fetchAllowedMints<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<AllowedMints, TAddress>> {
  const maybeAccount = await fetchMaybeAllowedMints(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeAllowedMints<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<AllowedMints, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeAllowedMints(maybeAccount);
}

export async function fetchAllAllowedMints(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Address[],
  config?: FetchAccountsConfig,
): Promise<Account<AllowedMints>[]> {
  const maybeAccounts = await fetchAllMaybeAllowedMints(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeAllowedMints(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Address[],
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<AllowedMints>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeAllowedMints(maybeAccount));
}
