/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import type {
  Account,
  Address,
  EncodedAccount,
  FetchAccountConfig,
  FetchAccountsConfig,
  FixedSizeCodec,
  FixedSizeDecoder,
  FixedSizeEncoder,
  MaybeAccount,
  MaybeEncodedAccount,
  ReadonlyUint8Array,
} from "@solana/kit";
import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
} from "@solana/kit";

export const REWARD_ACCUMULATOR_CONFIG_DISCRIMINATOR = new Uint8Array([
  121, 30, 187, 126, 122, 174, 181, 210,
]);

export function getRewardAccumulatorConfigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    REWARD_ACCUMULATOR_CONFIG_DISCRIMINATOR,
  );
}

export interface RewardAccumulatorConfig {
  discriminator: ReadonlyUint8Array;
  rewardAccumulatorProgram: Address;
  namespace: ReadonlyUint8Array;
}

export interface RewardAccumulatorConfigArgs {
  rewardAccumulatorProgram: Address;
  namespace: ReadonlyUint8Array;
}

export function getRewardAccumulatorConfigEncoder(): FixedSizeEncoder<RewardAccumulatorConfigArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["rewardAccumulatorProgram", getAddressEncoder()],
      ["namespace", fixEncoderSize(getBytesEncoder(), 8)],
    ]),
    (value) => ({
      ...value,
      discriminator: REWARD_ACCUMULATOR_CONFIG_DISCRIMINATOR,
    }),
  );
}

export function getRewardAccumulatorConfigDecoder(): FixedSizeDecoder<RewardAccumulatorConfig> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["rewardAccumulatorProgram", getAddressDecoder()],
    ["namespace", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getRewardAccumulatorConfigCodec(): FixedSizeCodec<
  RewardAccumulatorConfigArgs,
  RewardAccumulatorConfig
> {
  return combineCodec(
    getRewardAccumulatorConfigEncoder(),
    getRewardAccumulatorConfigDecoder(),
  );
}

export function decodeRewardAccumulatorConfig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<RewardAccumulatorConfig, TAddress>;
export function decodeRewardAccumulatorConfig<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<RewardAccumulatorConfig, TAddress>;
export function decodeRewardAccumulatorConfig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
):
  | Account<RewardAccumulatorConfig, TAddress>
  | MaybeAccount<RewardAccumulatorConfig, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getRewardAccumulatorConfigDecoder(),
  );
}

export async function fetchRewardAccumulatorConfig<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<RewardAccumulatorConfig, TAddress>> {
  const maybeAccount = await fetchMaybeRewardAccumulatorConfig(
    rpc,
    address,
    config,
  );
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeRewardAccumulatorConfig<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<RewardAccumulatorConfig, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeRewardAccumulatorConfig(maybeAccount);
}

export async function fetchAllRewardAccumulatorConfig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Address[],
  config?: FetchAccountsConfig,
): Promise<Account<RewardAccumulatorConfig>[]> {
  const maybeAccounts = await fetchAllMaybeRewardAccumulatorConfig(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeRewardAccumulatorConfig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Address[],
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<RewardAccumulatorConfig>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeRewardAccumulatorConfig(maybeAccount),
  );
}

export function getRewardAccumulatorConfigSize(): number {
  return 48;
}
