/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import type {
  Account,
  Address,
  EncodedAccount,
  FetchAccountConfig,
  FetchAccountsConfig,
  FixedSizeCodec,
  FixedSizeDecoder,
  FixedSizeEncoder,
  MaybeAccount,
  MaybeEncodedAccount,
  ReadonlyUint8Array,
} from "@solana/kit";
import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  transformEncoder,
} from "@solana/kit";

export const VOTE_MARKET_CONFIG_DISCRIMINATOR = new Uint8Array([
  172, 230, 34, 183, 39, 247, 10, 193,
]);

export function getVoteMarketConfigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    VOTE_MARKET_CONFIG_DISCRIMINATOR,
  );
}

export interface VoteMarketConfig {
  discriminator: ReadonlyUint8Array;
  scriptAuthority: Address;
  gaugemeister: Address;
  admin: Address;
  claimFee: number;
}

export interface VoteMarketConfigArgs {
  scriptAuthority: Address;
  gaugemeister: Address;
  admin: Address;
  claimFee: number;
}

export function getVoteMarketConfigEncoder(): FixedSizeEncoder<VoteMarketConfigArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["scriptAuthority", getAddressEncoder()],
      ["gaugemeister", getAddressEncoder()],
      ["admin", getAddressEncoder()],
      ["claimFee", getU16Encoder()],
    ]),
    (value) => ({ ...value, discriminator: VOTE_MARKET_CONFIG_DISCRIMINATOR }),
  );
}

export function getVoteMarketConfigDecoder(): FixedSizeDecoder<VoteMarketConfig> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["scriptAuthority", getAddressDecoder()],
    ["gaugemeister", getAddressDecoder()],
    ["admin", getAddressDecoder()],
    ["claimFee", getU16Decoder()],
  ]);
}

export function getVoteMarketConfigCodec(): FixedSizeCodec<
  VoteMarketConfigArgs,
  VoteMarketConfig
> {
  return combineCodec(
    getVoteMarketConfigEncoder(),
    getVoteMarketConfigDecoder(),
  );
}

export function decodeVoteMarketConfig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<VoteMarketConfig, TAddress>;
export function decodeVoteMarketConfig<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<VoteMarketConfig, TAddress>;
export function decodeVoteMarketConfig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
):
  | Account<VoteMarketConfig, TAddress>
  | MaybeAccount<VoteMarketConfig, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getVoteMarketConfigDecoder(),
  );
}

export async function fetchVoteMarketConfig<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<VoteMarketConfig, TAddress>> {
  const maybeAccount = await fetchMaybeVoteMarketConfig(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeVoteMarketConfig<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<VoteMarketConfig, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeVoteMarketConfig(maybeAccount);
}

export async function fetchAllVoteMarketConfig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Address[],
  config?: FetchAccountsConfig,
): Promise<Account<VoteMarketConfig>[]> {
  const maybeAccounts = await fetchAllMaybeVoteMarketConfig(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeVoteMarketConfig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Address[],
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<VoteMarketConfig>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeVoteMarketConfig(maybeAccount),
  );
}

export function getVoteMarketConfigSize(): number {
  return 106;
}
