/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import type {
  Account,
  Address,
  Codec,
  Decoder,
  EncodedAccount,
  Encoder,
  FetchAccountConfig,
  FetchAccountsConfig,
  MaybeAccount,
  MaybeEncodedAccount,
  Option,
  OptionOrNullable,
  ReadonlyUint8Array,
} from "@solana/kit";
import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
} from "@solana/kit";

export const VOTE_BUY_DISCRIMINATOR = new Uint8Array([
  155, 17, 20, 82, 247, 189, 203, 225,
]);

export function getVoteBuyDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(VOTE_BUY_DISCRIMINATOR);
}

export interface VoteBuy {
  discriminator: ReadonlyUint8Array;
  gauge: Address;
  /**
   * The mint of the token used to buy votes. This must be included in
   * [AllowedMints::mints] for the gauge.
   */
  mint: Address;
  amount: bigint;
  /** This amount or the amount field, whichever is less, will be distributed */
  maxAmount: Option<bigint>;
  /**
   * Anyone can create a vault for buying tokens. This is the creator
   * of the vault who is entitled to any incentives and is
   * allowed to add additional funds.
   */
  buyer: Address;
}

export interface VoteBuyArgs {
  gauge: Address;
  /**
   * The mint of the token used to buy votes. This must be included in
   * [AllowedMints::mints] for the gauge.
   */
  mint: Address;
  amount: number | bigint;
  /** This amount or the amount field, whichever is less, will be distributed */
  maxAmount: OptionOrNullable<number | bigint>;
  /**
   * Anyone can create a vault for buying tokens. This is the creator
   * of the vault who is entitled to any incentives and is
   * allowed to add additional funds.
   */
  buyer: Address;
}

export function getVoteBuyEncoder(): Encoder<VoteBuyArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["gauge", getAddressEncoder()],
      ["mint", getAddressEncoder()],
      ["amount", getU64Encoder()],
      ["maxAmount", getOptionEncoder(getU64Encoder())],
      ["buyer", getAddressEncoder()],
    ]),
    (value) => ({ ...value, discriminator: VOTE_BUY_DISCRIMINATOR }),
  );
}

export function getVoteBuyDecoder(): Decoder<VoteBuy> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["gauge", getAddressDecoder()],
    ["mint", getAddressDecoder()],
    ["amount", getU64Decoder()],
    ["maxAmount", getOptionDecoder(getU64Decoder())],
    ["buyer", getAddressDecoder()],
  ]);
}

export function getVoteBuyCodec(): Codec<VoteBuyArgs, VoteBuy> {
  return combineCodec(getVoteBuyEncoder(), getVoteBuyDecoder());
}

export function decodeVoteBuy<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<VoteBuy, TAddress>;
export function decodeVoteBuy<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<VoteBuy, TAddress>;
export function decodeVoteBuy<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<VoteBuy, TAddress> | MaybeAccount<VoteBuy, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getVoteBuyDecoder(),
  );
}

export async function fetchVoteBuy<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<VoteBuy, TAddress>> {
  const maybeAccount = await fetchMaybeVoteBuy(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeVoteBuy<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<VoteBuy, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeVoteBuy(maybeAccount);
}

export async function fetchAllVoteBuy(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Address[],
  config?: FetchAccountsConfig,
): Promise<Account<VoteBuy>[]> {
  const maybeAccounts = await fetchAllMaybeVoteBuy(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeVoteBuy(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Address[],
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<VoteBuy>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeVoteBuy(maybeAccount));
}
