/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import type { Address, ReadonlyUint8Array } from "@solana/kit";
import type {
  ParsedClaimToRewardAccumulatorInstruction,
  ParsedClaimVotePaymentInstruction,
  ParsedCommitVoteInstruction,
  ParsedCreateConfigInstruction,
  ParsedIncreaseVoteBuyInstruction,
  ParsedSetMaxAmountInstruction,
  ParsedUpdateAdminInstruction,
  ParsedUpdateAllowedMintsInstruction,
  ParsedUpdateClaimFeeInstruction,
  ParsedUpdateRewardAccumulatorConfigInstruction,
  ParsedUpdateScriptAuthorityInstruction,
  ParsedVoteBuyRefundInstruction,
  ParsedVoteInstruction,
} from "../instructions/index.js";
import { containsBytes, fixEncoderSize, getBytesEncoder } from "@solana/kit";

export const VOTE_MARKET_PROGRAM_ADDRESS =
  "VotAjwzAEF9ZLNAYEB1ivXt51911EqYGVu9NeaEKRyy" as Address<"VotAjwzAEF9ZLNAYEB1ivXt51911EqYGVu9NeaEKRyy">;

export enum VoteMarketAccount {
  VoteBuy = 0,
  VoteMarketConfig = 1,
  RewardAccumulatorConfig = 2,
  AllowedMints = 3,
}

export function identifyVoteMarketAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): VoteMarketAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([155, 17, 20, 82, 247, 189, 203, 225]),
      ),
      0,
    )
  ) {
    return VoteMarketAccount.VoteBuy;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([172, 230, 34, 183, 39, 247, 10, 193]),
      ),
      0,
    )
  ) {
    return VoteMarketAccount.VoteMarketConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([121, 30, 187, 126, 122, 174, 181, 210]),
      ),
      0,
    )
  ) {
    return VoteMarketAccount.RewardAccumulatorConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([207, 250, 95, 68, 245, 220, 110, 31]),
      ),
      0,
    )
  ) {
    return VoteMarketAccount.AllowedMints;
  }
  throw new Error(
    "The provided account could not be identified as a voteMarket account.",
  );
}

export enum VoteMarketInstruction {
  CreateConfig = 0,
  UpdateRewardAccumulatorConfig = 1,
  UpdateAdmin = 2,
  UpdateClaimFee = 3,
  UpdateScriptAuthority = 4,
  UpdateAllowedMints = 5,
  IncreaseVoteBuy = 6,
  ClaimVotePayment = 7,
  Vote = 8,
  ClaimToRewardAccumulator = 9,
  CommitVote = 10,
  SetMaxAmount = 11,
  VoteBuyRefund = 12,
}

export function identifyVoteMarketInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): VoteMarketInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([201, 207, 243, 114, 75, 111, 47, 189]),
      ),
      0,
    )
  ) {
    return VoteMarketInstruction.CreateConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([212, 118, 126, 80, 89, 132, 184, 215]),
      ),
      0,
    )
  ) {
    return VoteMarketInstruction.UpdateRewardAccumulatorConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([161, 176, 40, 213, 60, 184, 179, 228]),
      ),
      0,
    )
  ) {
    return VoteMarketInstruction.UpdateAdmin;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([192, 255, 140, 184, 150, 96, 181, 103]),
      ),
      0,
    )
  ) {
    return VoteMarketInstruction.UpdateClaimFee;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([57, 237, 52, 47, 112, 6, 101, 72]),
      ),
      0,
    )
  ) {
    return VoteMarketInstruction.UpdateScriptAuthority;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([146, 211, 161, 2, 10, 20, 94, 67]),
      ),
      0,
    )
  ) {
    return VoteMarketInstruction.UpdateAllowedMints;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([77, 209, 215, 129, 60, 249, 205, 53]),
      ),
      0,
    )
  ) {
    return VoteMarketInstruction.IncreaseVoteBuy;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([130, 32, 214, 224, 134, 130, 22, 171]),
      ),
      0,
    )
  ) {
    return VoteMarketInstruction.ClaimVotePayment;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([227, 110, 155, 23, 136, 126, 172, 25]),
      ),
      0,
    )
  ) {
    return VoteMarketInstruction.Vote;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([224, 2, 107, 127, 245, 68, 3, 89]),
      ),
      0,
    )
  ) {
    return VoteMarketInstruction.ClaimToRewardAccumulator;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([134, 97, 90, 126, 91, 66, 16, 26]),
      ),
      0,
    )
  ) {
    return VoteMarketInstruction.CommitVote;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([226, 133, 252, 54, 185, 15, 122, 154]),
      ),
      0,
    )
  ) {
    return VoteMarketInstruction.SetMaxAmount;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([178, 215, 141, 180, 246, 105, 86, 32]),
      ),
      0,
    )
  ) {
    return VoteMarketInstruction.VoteBuyRefund;
  }
  throw new Error(
    "The provided instruction could not be identified as a voteMarket instruction.",
  );
}

export type ParsedVoteMarketInstruction<TProgram extends string = ""> =
  | ({
      instructionType: VoteMarketInstruction.CreateConfig;
    } & ParsedCreateConfigInstruction<TProgram>)
  | ({
      instructionType: VoteMarketInstruction.UpdateRewardAccumulatorConfig;
    } & ParsedUpdateRewardAccumulatorConfigInstruction<TProgram>)
  | ({
      instructionType: VoteMarketInstruction.UpdateAdmin;
    } & ParsedUpdateAdminInstruction<TProgram>)
  | ({
      instructionType: VoteMarketInstruction.UpdateClaimFee;
    } & ParsedUpdateClaimFeeInstruction<TProgram>)
  | ({
      instructionType: VoteMarketInstruction.UpdateScriptAuthority;
    } & ParsedUpdateScriptAuthorityInstruction<TProgram>)
  | ({
      instructionType: VoteMarketInstruction.UpdateAllowedMints;
    } & ParsedUpdateAllowedMintsInstruction<TProgram>)
  | ({
      instructionType: VoteMarketInstruction.IncreaseVoteBuy;
    } & ParsedIncreaseVoteBuyInstruction<TProgram>)
  | ({
      instructionType: VoteMarketInstruction.ClaimVotePayment;
    } & ParsedClaimVotePaymentInstruction<TProgram>)
  | ({
      instructionType: VoteMarketInstruction.Vote;
    } & ParsedVoteInstruction<TProgram>)
  | ({
      instructionType: VoteMarketInstruction.ClaimToRewardAccumulator;
    } & ParsedClaimToRewardAccumulatorInstruction<TProgram>)
  | ({
      instructionType: VoteMarketInstruction.CommitVote;
    } & ParsedCommitVoteInstruction<TProgram>)
  | ({
      instructionType: VoteMarketInstruction.SetMaxAmount;
    } & ParsedSetMaxAmountInstruction<TProgram>)
  | ({
      instructionType: VoteMarketInstruction.VoteBuyRefund;
    } & ParsedVoteBuyRefundInstruction<TProgram>);
